# Generated by Django 4.2 on 2024-02-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('num_ratings', models.CharField(max_length=20, null=True)),
                ('published_year', models.IntegerField(null=True)),
                ('editions', models.IntegerField(null=True)),
                ('reviews_count', models.CharField(max_length=20, null=True)),
                ('image_url', models.URLField(null=True)),
                ('kindle_price', models.CharField(max_length=50, null=True)),
                ('book_format', models.CharField(max_length=100, null=True)),
                ('number_of_pages', models.IntegerField(null=True)),
                ('language', models.CharField(max_length=50, null=True)),
                ('isbn', models.CharField(max_length=20, null=True)),
                ('awards', models.TextField(null=True)),
            ],
            options={
                'unique_together': {('title', 'authors')},
            },
        ),
    ]
